### ISSUE TITLE
Upgrade to `mocha@8`

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-test#17]
https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#800--2020-06-10

One breaking change that stands out to me is: `The spec option no longer supports a comma-delimited list of files`.  I know that bedrock has the ability to specify test specs on the command line, I'm not sure if it relies on this `mocha` feature or not.

**Comment by dlongley** [comment]
We're using `moch@9` now, closing.
